language: csharp
os:
  - linux
  - osx
# .NET CLI require Ubuntu 14.04
dist: trusty
services:
  - docker
# .NET CLI requires OSX 10.11
osx_image: xcode7.2
# Ensure that .NET Core is installed
dotnet: 1.0.1
# Ensure Mono is installed
mono: latest
env:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    # Disable sending usage data to Microsoft
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
script:
  - ./build.sh -t TravisCI